// Generates src/hershey.ts from the hersheytext dataset (dev dependency).
// Run once with: node scripts/gen-hershey.mjs
// The Hershey "futural" font (Hershey Simplex) is the classic single-stroke
// routed/engraving grotesk used by plotters and CAD systems.
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";

const require = createRequire(import.meta.url);
const fonts = require("hersheytext/hersheytext.min.json");

const glyphs = {};
// Printable ASCII 33..126 from futural. chars[i] holds charCode 33+i;
// `o` is the half-advance (glyphs are centered), so advance = 2*o.
for (let code = 33; code <= 126; code++) {
  const g = fonts.futural.chars[code - 33];
  if (g?.d) glyphs[String.fromCharCode(code)] = { d: g.d, adv: 2 * Number(g.o) };
}
// Greek rho and delta live at the 'r' and 'd' slots of the greek font.
for (const [ch, slot] of [["ρ", "r"], ["δ", "d"]]) {
  const g = fonts.greek.chars[slot.charCodeAt(0) - 33];
  glyphs[ch] = { d: g.d, adv: 2 * Number(g.o) };
}

const out = `// GENERATED by scripts/gen-hershey.mjs — do not edit by hand.
//
// Single-stroke glyph outlines from the Hershey "futural" font (Hershey
// Simplex — the routed grotesk lettering used by plotters and CAD), plus
// ρ and δ from the Hershey Greek font. Each glyph is an SVG path meant to
// be STROKED, never filled. Coordinates are y-down with the baseline at
// y = ${22} and a cap height of ${21} units; "adv" is the horizontal
// advance to the next character in the same units.

export interface Glyph {
  d: string;
  adv: number;
}

/** Baseline y-coordinate inside a glyph's own coordinate system. */
export const BASELINE = 22;

/** Height of a capital letter in glyph units — scale text by size ÷ CAP. */
export const CAP = 21;

/** Advance used for the space character, in glyph units. */
export const SPACE_ADV = 14;

export const GLYPHS: Record<string, Glyph> = ${JSON.stringify(glyphs)};
`;

writeFileSync(new URL("../src/hershey.ts", import.meta.url), out);
console.log(`wrote src/hershey.ts with ${Object.keys(glyphs).length} glyphs`);
